[project]
name = "langraph-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langgraph>=0.6.8",
    "notebook>=7.4.7",
    "pandas>=2.3.3",
    "python-dotenv>=1.1.1",
]
